config/routes.rb
Diploma::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  authenticated :user do
    root to: "articles#index", as: :user_root
  end
  root to: "pages#landing"

  resources :articles
  resources :comments
  resources :users do
    post 'follow', on: :member
    delete 'unfollow', on: :member
  end
  resources :documents, only: [:create, :destroy]
  match '/documents' => 'documents#create', via: :patch
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :documents

  validates :text, :title, presence: true
  
  accepts_nested_attributes_for :documents, reject_if: :wrong_parameters?
  
  private
  
  def wrong_parameters?(attributes)
    !(attributes[:title] && attributes[:file])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_filter :remove_unrelated_documents, only: [:create, :update]

  def index
    @articles = current_user.articles.includes(:documents, comments: [:subcomments])
  end

  def new 
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      attach_documents
      flash[:success] = "Your article was successfully created"
      redirect_to user_root_path
    else
      flash[:error] = "Error occured"
      render "new"
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = current_user.comments.build(commentable: @article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id]) 
    @article.update_attributes(article_params)
    attach_documents
    redirect_to @article
  end

  def destroy
    article = Article.find(params[:id])
    if article.destroy
      flash[:success] = "Your article was successfully deleted"
      redirect_to user_root_path
    else
      render 'nothing'
    end
  end

  private 

  def article_params
    params.require(:article).permit(:title, :text)
  end
  
  def attach_documents
    Document.where(id: document_ids).update_all(article_id: @article.id)
  end
  
  def document_ids
    params[:article][:documents_attributes].map {|document| document[:id]} if params[:article][:documents_attributes]
  end
end

app/views/articles/_form.html.haml
= simple_form_for @article, html: { class: 'form form-horizontal' } do |article_form|
  .horizontal-forms
    .wrapper
      .main-form
        .field
          = article_form.input :title
        .field
          = article_form.input :text, input_html: {class: 'summernote'}

      .sub-form
        .documents-container
          .title
            = fa_icon 'caret-down'
            Documents
          = simple_fields_for :documents, Document.new do |document_form|
            %ul.documents-list
              - @article.documents.each do |document|
                %li
                  = square('document') do
                    .content
                      .preview
                        - if document.file.image?
                          = image_tag document.file.thumb
                        - else
                          = image_tag document.decorate.document_icon
                      .name= document.filename
                    = link_to document, class: 'content remove' do
                      = fa_icon 'trash-o'
              %li.add-document
                = square('upload-button') do
                  .content
                    = fa_icon(:plus)
                    = document_form.file_field :file, 'data-url' => documents_path

    .form-actions
      = link_to 'Go back', user_root_path, class: 'btn btn-default'
      = article_form.button :submit, class: 'btn btn-success'

app/views/articles/edit.html.haml
.page
  .page-header
    %h1.page-title Edit Article
    .actions= link_to 'Go back', user_root_path, class: 'btn btn-default'
  =render 'articles/form'

app/views/articles/index.html.haml
.page
  .page-header
    %h1.page-title Articles list 
    .actions= link_to "New article", new_article_path, class: 'btn btn-success'

  %ul.articles
    - @articles.each do |article| 
      %li.article-wrapper
        %span.actions-wrapper
          =link_to '', edit_article_path(article), class: 'fa fa-pencil'
          =link_to '', article_path(article), method: :delete, confirm: "Are you sure?", class: 'fa fa-trash-o'
        = link_to article, class: 'article' do
          .header
            .text= article.title
          .content= article.decorate.short_text
          .meta-info
            .author= 'Author: ' + article.user.email
            .updated= 'Updated at: ' + article.updated_at.to_s
            %ul
              %li.documents= 'Documents: ' + article.documents.count.to_s
              %li.comments= 'Comments: ' + article.decorate.comments_count.to_s

  -#      .documents
  -#        - article.documents.each do |document|
  -#          - if document.file.image?
  -#            .document= image_tag document.file_url(:thumb)
  -#          - else 
  -#            .document= link_to document.title ,document.file.url, target: :_blank

app/views/articles/new.html.haml
.page
  .page-header
    %h1.page-title New Article
    .actions= link_to 'Go back', user_root_path, class: 'btn btn-default'

  =render 'articles/form'

app/views/articles/show.html.haml
#article-show.container
  .row
    .col-sm-8.blog-main
      .blog-post
        %h2.blog-post-title=@article.title
        .blog-post-meta
          .user-info.meta-info
            = link_to @article.user do
              .initials
                = fa_icon 'user'
                = @article.user.decorate.initials
              .description= @article.user.description
          .date-info.meta-info
            = @article.updated_at
          .follow-actions.meta-info
            = current_user.decorate.subscription_link_for @article.user
        %p= @article.text.html_safe
        
      - unless @article.documents.empty?
        .documents-container
          .title
            = fa_icon 'caret-down'
            Documents
          %ul.documents-list
            - @article.documents.each do |document|
              %li
                = square('document') do
                  .content
                    .preview
                      - if document.file.image?
                        %a.fancy{ href: document.file.huge.url, rel: "images" }
                          = image_tag document.file.thumb
                      - else
                        = link_to document.file.url, target: :_blank do
                          = image_tag document.decorate.document_icon
                    .name= document.filename
        
      .discussion
        .title 
          =fa_icon 'comment' 
          Discussion
        = render @article.comments

        = simple_form_for @comment, method: :post, html: {class: 'main-comment-form'}, remote: true, format: :json do |f|
          = f.input :text, as: :text,label: false, input_html: {class: 'form-control col-sm-12'}
          = f.input :commentable_type, as: :hidden
          = f.input :commentable_id, as: :hidden
          = f.input :user_id, as: :hidden
          = f.button :submit, 'Post comment', class: 'post-comment btn btn-info'

    .col-sm-3.col-sm-offset-1.blog-sidebar
      .sidebar-module.sidebar-module-inset
        %h4 About
        %p
          Etiam porta
          %em sem malesuada magna
          mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.
      .sidebar-module
        %h4 Archives
        %ol.list-unstyled
          %li
            %a{:href => "#"} January 2014
          %li
            %a{:href => "#"} December 2013
          %li
            %a{:href => "#"} November 2013
          %li
            %a{:href => "#"} October 2013
          %li
            %a{:href => "#"} September 2013
          %li
            %a{:href => "#"} August 2013
          %li
            %a{:href => "#"} July 2013
          %li
            %a{:href => "#"} June 2013
          %li
            %a{:href => "#"} May 2013
          %li
            %a{:href => "#"} April 2013
          %li
            %a{:href => "#"} March 2013
          %li
            %a{:href => "#"} February 2013
      .sidebar-module
        %h4 Elsewhere
        %ol.list-unstyled
          %li
            %a{:href => "#"} GitHub
          %li
            %a{:href => "#"} Twitter
          %li
            %a{:href => "#"} Facebook