config/routes.rb
Diploma::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  authenticated :user do
    root to: "articles#index", as: :user_root
  end
  root to: "pages#landing"

  resources :articles
  resources :comments
  resources :users do
    post 'follow', on: :member
    delete 'unfollow', on: :member
  end
  resources :documents, only: [:create, :destroy]
  match '/documents' => 'documents#create', via: :patch
end

app/views/layouts/_flash_message.html.haml
-if flash[:error] || flash[:alert] 
  .flash-message
    .text.alert.alert-danger
      = flash[:error] || flash[:alert]
      %a.hide-flash=fa_icon 'times'
-if flash[:notice] 
  .flash-message
    .text.alert.alert-info
      = flash[:notice]
      %a.hide-flash=fa_icon 'times'
-if flash[:success]
  .flash-message
    .text.alert.alert-success
      = flash[:success]
      %a.hide-flash=fa_icon 'times'

app/views/layouts/_footer.html.haml
#footer
  .container
    .row
      .left 
        = link_to 'Official NMU website', 'http://www.nmu.org.ua/ua/'
      .right
        %span.copyright © 2014 NMU Blog

app/views/layouts/_navbar.html.haml
.navbar.navbar-inverse{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} 
        =fa_icon 'university'
        NMU Blog
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to "Home", articles_path
        %li
          %a About
        %li
          %a Contact
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            = current_user.email
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to 'Settings', edit_user_registration_path 
            %li
              = link_to 'Log out', destroy_user_session_path, method: :delete
            %li.divider
            %li.dropdown-header Nav header
            %li
              %a{:href => "#"} Separated link

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Diploma
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{ body_attributes }
    .outer-wrapper
      = render 'layouts/navbar'
      .container
        = render 'layouts/flash_message'
        = yield
      .footer-buffer
    = render 'layouts/footer'

app/views/layouts/unauthorized.html.haml
!!!
%html
  %head
    %title Diploma
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .fullscreen-container= yield